"""tracks: audio mp3 e links de distribuicao

Revision ID: 5b1e34d8feb5
Revises: d864774756fa
Create Date: 2026-09-11 01:24:09.804692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1e34d8feb5'
down_revision: Union[str, Sequence[str], None] = 'd864774756fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('audio_path', sa.String(length=500), nullable=True))
    op.add_column('tracks', sa.Column('audio_original_filename', sa.String(length=255), nullable=True))
    op.add_column('tracks', sa.Column('audio_size', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_mime', sa.String(length=100), nullable=True))
    op.add_column('tracks', sa.Column('links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'links')
    op.drop_column('tracks', 'audio_mime')
    op.drop_column('tracks', 'audio_size')
    op.drop_column('tracks', 'audio_original_filename')
    op.drop_column('tracks', 'audio_path')
    # ### end Alembic commands ###
