"""tracks campos de criacao com IA

Revision ID: 77a1f242f30c
Revises: b3c7e2a9d1f4
Create Date: 2026-09-12 01:17:53.979442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a1f242f30c'
down_revision: Union[str, Sequence[str], None] = 'b3c7e2a9d1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('ai_assisted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('tracks', sa.Column('ai_platform', sa.String(length=255), nullable=True))
    op.add_column('tracks', sa.Column('prompt', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('lyrics_original', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('style_positive', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('style_negative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'style_negative')
    op.drop_column('tracks', 'style_positive')
    op.drop_column('tracks', 'lyrics_original')
    op.drop_column('tracks', 'prompt')
    op.drop_column('tracks', 'ai_platform')
    op.drop_column('tracks', 'ai_assisted')
    # ### end Alembic commands ###
