"""remove prompt da faixa (igual ao estilo positivo)

Revision ID: be94876055a0
Revises: 77a1f242f30c
Create Date: 2026-09-12 01:23:30.221460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be94876055a0'
down_revision: Union[str, Sequence[str], None] = '77a1f242f30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('prompt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
