"""tracks: traducao da letra

Revision ID: ca50613ba645
Revises: 5b1e34d8feb5
Create Date: 2026-09-11 01:32:56.506858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca50613ba645'
down_revision: Union[str, Sequence[str], None] = '5b1e34d8feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'translation')
    # ### end Alembic commands ###
